version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - bodyclose
    - errname
    - errorlint
    - gocritic
    - gosec
    - misspell
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
        - experimental
        - opinionated
    gosec:
      severity: medium
      confidence: medium
    govet:
      enable-all: true
    revive:
      rules:
        - name: exported
          severity: warning
        - name: indent-error-flow
          severity: warning
        - name: var-naming
          severity: warning
        - name: package-comments
          severity: warning
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
